adding all etl to elasticsearch backend supported

diff --git a/src/lib/hotspot b/src/lib/hotspot
--- a/src/lib/hotspot
+++ b/src/lib/hotspot
@@ -1,7 +1,8 @@
 get_info_elasticsearch() {
   if [[ "${collector_storage_profile}" == *"elasticsearch"* ]] && [ "${elasticsearch_url}" ]; then
     get_curl_options
-    es_payload=$(curl ${curl_options} -H "apikey: ${client_api_key}" -H "Content-Type: application/json" "${elasticsearch_url}/hnt-${client_api_key,,}/_search?q=_id:hotspot.${a}.collector.info" | jq '.hits.hits[]._source' 2>/dev/null) || log_err "could not retrieve [info] elasticsearch results"
+    es_info_payload=$(curl ${curl_options} -H "apikey: ${client_api_key}" -H "Content-Type: application/json" "${elasticsearch_url}/hnt-${client_api_key,,}/_search?q=_id:hotspot.${a}.collector.info" | jq '.hits.hits[]._source' 2>/dev/null) || log_err "could not retrieve [info] elasticsearch results"
+    log_debug "get.info.elasticsearch response - [ $(jq -r -c '.data.name' <<< "${es_info_payload}" 2>/dev/null) ]"
   fi
 }
 
@@ -12,10 +13,11 @@ get_hotspot_name() {
 
   if [[ "${collector_storage_profile}" == *"elasticsearch"* ]] && [ "${elasticsearch_url}" ]; then
     get_info_elasticsearch
-    name=$(jq -r '.data.name' <<< "${es_payload}" 2>/dev/null) || log_err "could not get the miner name"   
+    name=$(jq -r '.data.name' <<< "${es_info_payload}" 2>/dev/null) || log_err "could not get the miner name"   
   fi
 
   name=${name:-"unknown"}
+  log_debug "get.hotspot.name [${name}]"
 }
 
 get_relayed_status() {
@@ -25,7 +27,7 @@ get_relayed_status() {
 
   if [[ "${collector_storage_profile}" == *"elasticsearch"* ]] && [ "${elasticsearch_url}" ]; then
     get_info_elasticsearch
-    relayed_status=$(jq -r '.data.status.listen_addrs[]' <<< "${es_payload}" 2>/dev/null | grep "${relayed_status_ports// /\|}" | wc -l) || true
+    relayed_status=$(jq -r '.data.status.listen_addrs[]' <<< "${es_info_payload}" 2>/dev/null | grep "${relayed_status_ports// /\|}" | wc -l) || true
   fi
 }
 
@@ -36,6 +38,6 @@ get_online_status() {
 
   if [[ "${collector_storage_profile}" == *"elasticsearch"* ]] && [ "${elasticsearch_url}" ]; then
     get_info_elasticsearch
-    online_status=$(jq -r '.data.status.online' <<< "${es_payload}" 2>/dev/null | grep online | wc -l) || true
+    online_status=$(jq -r '.data.status.online' <<< "${es_info_payload}" 2>/dev/null | grep online | wc -l) || true
   fi
 }
diff --git a/src/lib/logger b/src/lib/logger
--- a/src/lib/logger
+++ b/src/lib/logger
@@ -1,21 +1,21 @@
 log_info() {
   msg=${1:-""}
-  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: [$id] - ${msg}" >> "${logpath}/${logfile}"
+  echo "{ \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S)\", \"level\": \"INFO\", \"thread\": \"${id}\", \"message\": \"${msg}\" }" >> "${logpath}/${logfile}" || true
 }
 
 log_warn() {
   msg=${1:-""}
-  echo "$(date +%Y-%m-%dT%H:%M:%S) [WARN]: [$id] - ${msg}" >> "${logpath}/${logfile}"
+  echo "{ \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S)\", \"level\": \"WARN\", \"thread\": \"${id}\", \"message\": \"${msg}\" }" >> "${logpath}/${logfile}" || true
 }
 
 log_err() {
   msg=${1:-""}
-  echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: [$id] - ${msg}" >> "${logpath}/${logfile}"
+  echo "{ \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S)\", \"level\": \"ERROR\", \"thread\": \"${id}\", \"message\": \"${msg}\" }" >> "${logpath}/${logfile}" || true
 }
 
 log_debug() {
   msg=${1:-""}
   if [ "${debug}" == "true" ]; then
-    echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: [$id] - ${msg}" >> "${logpath}/${logfile}"
+    echo -e "{ \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S)\", \"level\": \"DEBUG\", \"thread\": \"${id}\", \"message\": \"${msg}\" }" >> "${logpath}/${logfile}" || true
   fi
 }
