allow port only to api

diff --git a/src/lib/hotspot b/src/lib/hotspot
--- a/src/lib/hotspot
+++ b/src/lib/hotspot
@@ -1,11 +1,28 @@
+get_hotspot_info_elasticsearch() {
+  if [[ "${collector_storage_profile}" == *"elasticsearch"* ]] && [ "${elasticsearch_url}" ]; then
+    get_curl_options
+    es_payload=$(curl ${curl_options} -H "apikey: ${client_api_key}" -H "Content-Type: application/json" "${elasticsearch_url}/hnt-${client_api_key,,}.${global_day}/_search?q=_id:hotspot.${a}.collector.info" | jq '.hits.hits[]._source' 2>/dev/null) || log_err "could not retrieve [info] elasticsearch results"
+  fi
+}
+
 get_hotspot_name() {
-  name=$(jq -r '.data.name' "${data_dir}/${a}/info" 2>/dev/null) || log_err "could not get the miner name"
+  if [[ "${collector_storage_profile}" == *"local"* ]] || [ ! "${collector_storage_profile}" ]; then
+    name=$(jq -r '.data.name' "${data_dir}/${a}/info" 2>/dev/null) || log_err "could not get the miner name"
+  fi
+
+  if [[ "${collector_storage_profile}" == *"elasticsearch"* ]] && [ "${elasticsearch_url}" ]; then
+    name=$(jq -r '.data.name' <<< "${es_payload}" 2>/dev/null) || log_err "could not get the miner name"   
+  fi
 }
 
 get_relayed_status() {
-  relayed_status=$(jq -r '.data.status.listen_addrs[]' "${data_dir}"/${a}/info 2>/dev/null | grep 44158 | wc -l) || true
+  if [[ "${collector_storage_profile}" == *"local"* ]] || [ ! "${collector_storage_profile}" ]; then
+    relayed_status=$(jq -r '.data.status.listen_addrs[]' "${data_dir}"/${a}/info 2>/dev/null | grep 44158 | wc -l) || true
+  fi
 }
 
 get_online_status() {
-  online_status=$(jq -r '.data.status.online' "${data_dir}"/${a}/info 2>/dev/null | grep online | wc -l) || true
+  if [[ "${collector_storage_profile}" == *"local"* ]] || [ ! "${collector_storage_profile}" ]; then
+    online_status=$(jq -r '.data.status.online' "${data_dir}"/${a}/info 2>/dev/null | grep online | wc -l) || true
+  fi
 }
