prime time

diff --git a/src/lib/reward_totals b/src/lib/reward_totals
--- a/src/lib/reward_totals
+++ b/src/lib/reward_totals
@@ -23,10 +23,12 @@ fi
 
 
 addresses=$(< ../conf/address.list)
-current_day=$(date +%Y-%m-%d -u)
-current_time=$(date +%H:%M -u)
-timestamp_30d=$(date +%Y-%m-%d -u --date="30 days ago")
-id=reward_total
+minutes_ago=$(date -u --date="15 minutes ago" +%s)
+hour_ago=$(date -u --date="1 hour ago" +%s)
+one_day_ago=$(date -u --date="1 days ago" +%s)
+seven_days_ago=$(date -u --date="7 days ago" +%s)
+thirty_days_ago=$(date -u --date="30 days ago" +%s)
+id=reward_total.etl
 
 reward_total() {
   echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO] [$id]: getting data" >> "${logpath}/${logfile}"
@@ -37,65 +39,33 @@ reward_total() {
   rewards_7d=0
   rewards_30d=0
 
-  rewards=$(jq -r '.data[].timestamp' <<< "${data}")
-  hour=$(echo "${current_time}" | awk -F ':' '{print $1}')
-  minute=$(echo "${current_time}" | awk -F ':' '{print $2}')
+  rewards=$(jq -r '.data[].timestamp' "${data_dir}/${a}"/*.rewards | sort -u)
 
   [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards timestamps\n${rewards}\n\n" >> "${logpath}/${logfile}"
-  [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: captured UTC time ${hour}:${minute}" >> "${logpath}/${logfile}"
 
-  for r in ${reward_data}; do
-    clean_time=$(echo "${r}" | sed 's%.*T%%;s%\..*%%')
-    h=$(echo "${clean_time}" | awk -F ':' '{print $1}')
-    m=$(echo "${clean_time}" | awk -F ':' '{print $2}')
-    m_loss=$((minute-16))
-    rmh=${h}
-    rmm=${m}
+  for r in ${rewards}; do
+    time=$(date -d ${r} +%s)    
 
-    if [ "${m_loss}" -lt "0" ]; then
-      m_loss=$(echo "${m_loss}" | sed 's%-%%')
-      m_loss=$((60-m_loss))
-      rmh=${hour}
-      rmm=${minute}
-    fi
-    
-    if [ "${rmh}" -eq "${hour}" ] && [ "${rmm}" -le "${minute}" ] && [ "${m}" -ge "${m_loss}" ]; then
+    if [ "${seven_days_ago}" -le "${time}" ]; then
       ((rewards_15m++)) || true
     fi
 
-    if [ "${h}" -eq "${hour}" ]; then
+    if [ "${hour_ago}" -le "${time}" ]; then
       ((rewards_1h++)) || true
     fi
 
-    if [[ "${r}" == *"${current_day}"* ]]; then
+    if [ "${one_day_ago}" -le "${time}" ]; then
       ((rewards_1d++)) || true
     fi
 
-    ((rewards_7d++)) || true
-    ((rewards_30d++)) || true
-    rewards=$(echo "${rewards}" | sed "s%${r}%%")
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: verifying reward timestamp ${r}" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: cleaning up timestamp ${clean_time}" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: clean timestamp H(${h}) M(${m})" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: setting 15 minute maximum float ${m_loss}" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: minute data verification ${m} less than or equal to ${minute} and greater than or equal to ${m_loss}" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: hour data verification ${h} equals ${hour}" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: day data verification reward timestamp ${r} is in current day ${current_day}" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: removing ${r} from the rewards list" >> "${logpath}/${logfile}"
-    [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: remaining rewards timestamps\n${rewards}\n\n" >> "${logpath}/${logfile}"
+    if [ "${seven_days_ago}" -le "${time}" ]; then
+      ((rewards_7d++)) || true
+    fi
+
+    if [ "${thirty_days_ago}" -le "${time}" ]; then
+      ((rewards_30d++)) || true
+    fi
   done
-
-  rewards_1hour=$(echo "${rewards}" | grep "${current_day}" | sed 's%.*T%%;s%:.*%%' | grep "${hour}" | wc -l | tr -dc .[:print:]. || echo 0)
-  rewards_1h=$((rewards_1h + rewards_1hour))
-
-  rewards_1day=$(echo "${rewards}" | grep "${current_day}" | wc -l | tr -dc .[:print:]. || echo 0)
-  rewards_1d=$((rewards_1d + rewards_1day))
-
-  rewards_7day=$(echo "${rewards}" | grep "${current_day}\|$(date +%Y-%m-%d --date="1 day ago" -u)\|$(date +%Y-%m-%d --date="2 days ago" -u)\|$(date +%Y-%m-%d --date="3 days ago" -u)\|$(date +%Y-%m-%d --date="4 days ago" -u)\|$(date +%Y-%m-%d --date="5 days ago" -u)\|$(date +%Y-%m-%d --date="6 days ago" -u)\|$(date +%Y-%m-%d --date="7 days ago" -u)" | wc -l | tr -dc .[:print:]. || echo 0)
-  rewards_7d=$((rewards_7d + rewards_7day))
-
-  rewards_30day=$(echo "${rewards}" | wc -l | tr -dc .[:print:]. || echo 0)
-  rewards_30d=$((rewards_30d + rewards_30day))
 
   [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards in 15 minute ${rewards_15m}" >> "${logpath}/${logfile}"
   [ "${debug}" == "true" ] && echo -e "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: rewards in 1 hour ${rewards_1h}" >> "${logpath}/${logfile}"
@@ -121,36 +91,16 @@ ${project}_reward_7d{instance="${name}",address="${a}"} ${rewards_7d}
 ${project}_reward_30d{instance="${name}",address="${a}"} ${rewards_30d}
 EOF
 
-  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: reward data pushed to http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}" >> "${logpath}/${logfile}"
+  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO] [$id]: data pushed to http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}" >> "${logpath}/${logfile}"
 }
-
-witness() {
-  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: getting witness data" >> "${logpath}/${logfile}"
-  witnessed_count=$(jq '.data[].name' "${data_dir}/${a}/${data_format}.witnessed"  | wc -l)
-  witnesses_count=$(jq '.data[].name' "${data_dir}/${a}/${data_format}.witnesses" | wc -l)
-
-  cat <<EOF | curl -s --data-binary @- http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}
-# HELP ${project}_witnessed miners
-# TYPE ${project}_witnessed gauge
-${project}_witnessed{instance="${name}",address="${a}"} ${witnessed_count}
-# HELP ${project}_witnesses miners
-# TYPE ${project}_witnesses gauge
-${project}_witnesses{instance="${name}",address="${a}"} ${witnesses_count}
-EOF
-
-  echo "$(date +%Y-%m-%dT%H:%M:%S) [INFO]: witness data pushed to http://${prometheus_pg_host}:${prometheus_pg_port}/metrics/job/${project}" >> "${logpath}/${logfile}"
-  [ "${debug}" == "true" ] && echo "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: witnesses count ${witnesses_count}" >> "${logpath}/${logfile}"
-  [ "${debug}" == "true" ] && echo "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: witnessed count ${witnessed_count}" >> "${logpath}/${logfile}"
-}
-
 
 if [ "${hotspot_monitor}" == "true" ]; then
   for a in ${addresses}; do
-    name=$(jq -r '.data.name' "${data_dir}/${a}/info") || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR]: could not get the miner name" >> "${logpath}/${logfile}"
+    name=$(jq -r '.data.name' "${data_dir}/${a}/info") || echo "$(date +%Y-%m-%dT%H:%M:%S) [ERROR] [$id]: could not get the miner name" >> "${logpath}/${logfile}"
 
-    #reward_total &
+    reward_total
   done
 else
-  [ "${debug}" == "true" ] && echo "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG]: Hotspot monitor collection is disabled. Hint: (hotspot_monitor=false)" >> "${logpath}/${logfile}"
+  [ "${debug}" == "true" ] && echo "$(date +%Y-%m-%dT%H:%M:%S) [DEBUG] [$id]: Hotspot monitor collection is disabled. Hint: (hotspot_monitor=false)" >> "${logpath}/${logfile}"
   true
 fi
